- src/blocks/led/virtual-circuit.ts
- src/components/electroblocks/home/LedColorChanger.svelte
- src/components/electroblocks/home/Simulator.svelte
- src/core/virtual-circuit/paint.ts
- src/core/virtual-circuit/svg-create.ts
- src/core/virtual-circuit/wire.ts
- src/microcontrollers/arduino_mega/profile.ts
- src/microcontrollers/arduino_uno/profile.ts
- We don't want to redraw the components every time the blocks change.  The reason is that they can drag and drop the svgs and position them.  We don't save that information right now.  We might in the future.  I am thinking it need to go into a separate data store.
- LED can now have their own custom colors.  You double click on the led and change the color to whatever you want.
> Led Color + No Redraw Components

- src/routes/_layout.svelte
> Fixed Lesson Page Load

- package-lock.json
- src/blocks/math/blocks.ts
- src/blocks/math/blocktovalue.math_number.test.ts
- src/blocks/math/blocktovalue.ts
- src/blocks/math/generators.ts
- src/blocks/math/toolbox.ts
- src/core/blockly/dto/block.type.ts
- src/core/frames/transformer/block-to-value.factories.ts
Added math property block to make it easy to tell stuff about the numbers.  I noticed the need for this when making neo-pixel videos and using the loop.
> Math Property Block

- src/blocks/led_matrix/blocktoframe.ts
- src/blocks/led_matrix/generators.ts
- src/blocks/led_matrix/virtual-circuit.ts
To fix the bugs with the LED Matrix.  Things like x and y were reversed and fixed the simulator too.
> Led Matrix Bug

- src/blocks/bluetooth/blocktoframe.test.ts
- src/blocks/button/blocktoframe.test.ts
- src/blocks/ir_remote/blocktoframe.test.ts
- src/blocks/lcd_screen/blocktoframe.test.ts
- src/blocks/message/blocktoframe.test.ts
- src/blocks/message/blocktoframe.ts
- src/blocks/neopixels/blocktoframe.test.ts
- src/blocks/rfid/blocktoframe.test.ts
- src/blocks/rgbled/blocktoframe.test.ts
- src/blocks/temperature/blocktoframe.test.ts
- src/blocks/time/blocktoframe.delay.ts
- src/blocks/time/blocktoframe.time.test.ts
- src/blocks/ultrasonic_sensor/blocktoframe.test.ts
- src/core/frames/arduino.frame.ts
- src/core/frames/event-to-frame.factory.ts
- src/core/frames/transformer/frame-transformer.helpers.ts
I believe that most browsers/computers will only be able to handle 5000 frames being generated. I am thinking about Chromebooks.  Because of this, I want to put a max frame at 5000 frames.  I might decide to a continue statement as well.
> Maximum Frame Bug

- src/core/blockly/registerEvents.ts
If someone changes the for loop variable or another variable name, it does not generate new code or frames.
https://github.com/ElectroBlocks/ElectroBlocks/issues/140
> Regenerate when variables change

- src/core/blockly/actions/actions.ts
- src/core/blockly/actions/updateLcdScreenPrintBlock.test.ts
- src/core/blockly/actions/updateLcdScreenPrintBlock.ts
- src/core/blockly/registerEvents.ts
- src/core/blockly/updater.ts
To fix the rows on the LCD screen,  I need to write a few tests before merging this in.
> Lcd Row Block Fix

- src/blocks/color/generators.ts
- src/blocks/lcd_screen/generators.ts
- src/blocks/loops/generators.ts
- src/core/blockly/generators/arduino.ts
To remove the extra code by the simple repeat block and the color value blocks.
> Extra code bug fix

- src/blocks/analogsensor/blocks.ts
- src/blocks/bluetooth/blocks.ts
- src/blocks/button/blocks.ts
- src/blocks/digitalsensor/blocks.ts
- src/blocks/ir_remote/blocks.ts
- src/blocks/joystick/blocks.ts
- src/blocks/message/blocks.ts
- src/blocks/rfid/blocks.ts
- src/blocks/temperature/blocks.ts
- src/blocks/thermistor/blocks.ts
- src/blocks/ultrasonic_sensor/blocks.ts
- src/core/blockly/actions/saveSensorSetupBlockData.test.ts
- src/core/blockly/actions/saveSensorSetupBlockData.ts
- src/core/blockly/transformers/block.transformer.test.ts
Allows users to select copy all for sensors setup block
> Copy all block

- package-lock.json
- package.json
We are upgrading firebase to latest package to see if everything still works.
> Upgrade Firebase

- src/blocks/motors/virtual-circuit.ts
Added some space between two motors
> Added some space between two motors

- src/blocks/led/led.svg
The off text was getting slightly cut off on the LED.  I wanted to do a minor fix in inkscape.
> Fixed off on the LED

- src/blocks/fastled/blocks.ts
- src/core/blockly/actions/actions.ts
- src/core/blockly/actions/fastLedSetAllColorsUpdateBlock.test.ts
- src/core/blockly/actions/fastLedSetAllColorsUpdateBlock.ts
- src/core/blockly/registerEvents.ts
- src/core/blockly/updater.ts
This will shrink the fastled color block into a the size of the fast leds in the setup block.  This still needs a test.
> Set all FastLed Color Block Shrinker

- src/blocks/button/blocks.ts
- src/blocks/button/blocktoframe.test.ts
- src/blocks/button/blocktoframe.ts
- src/blocks/button/generators.ts
- src/blocks/button/toolbox.ts
- src/core/blockly/dto/block.type.ts
- src/core/blockly/generators/arduino.ts
- src/core/frames/transformer/block-to-frame.transformer.ts
- src/routes/download/+page.svelte
To get a release button block to work.
> Got Button Release Block to Work

- src/routes/code/+page.svelte
- Zoom in 
- Zoom out
- Copy Code
> Code View Improvements

- src/blocks/button/blocks.ts
- src/blocks/button/blocktoframe.test.ts
- src/blocks/button/blocktoframe.ts
- src/blocks/button/button.svg
- src/blocks/button/component-state-to-id.ts
- src/blocks/button/generators.ts
- src/blocks/button/setupblocktocomponentstate.ts
- src/blocks/button/state.ts
- src/blocks/button/virtual-circuit.ts
- src/core/frames/arduino-component-id.ts
- src/core/virtual-circuit/wire.ts
We want to get input and input pull resistors working.  To do this we need to wire power to the button if it's INPUT and if it's INPUT_PULLUP it goes to ground. There is also HIGH vs LOW.
> Button with INPUT and INPUT PULLUP

- src/blocks/button/blocktoframe.test.ts
- src/blocks/button/generators.ts
- src/blocks/button/push_button.svg
- src/blocks/button/virtual-circuit.ts
- src/blocks/joystick/frame.test.ts
- src/blocks/motors/blocktoframe.test.ts
- src/core/virtual-circuit/svg-create.ts
- src/core/virtual-circuit/svg-string.ts
- src/core/virtual-circuit/wire.ts
To get the breaboard button working
> Got the breadboard button to work

- src/blocks/arduino/generators.ts
- src/blocks/led/generators.ts
- src/blocks/time/generators.ts
- src/core/blockly/generators/index.ts
- src/core/blockly/generators/python.ts
- src/core/blockly/helpers/workspace.helper.ts
- src/core/blockly/registerEvents.ts
To modify @uv547756 code so that it would generate Python code using the generators.
> Basic Python Generator Working

- src/blocks/logic/generators.ts
All python generators for the Logic category are working.
> Logic block

- src/components/electroblocks/Blockly.svelte
- src/core/blockly/startBlockly.ts
- src/core/blockly/toolbox.ts
- src/core/microcontroller/microcontroller.ts
- src/firebase/model.ts
Have the toolbox reload code based on the language and microcontroller type.  In this example pr Python will show the Thermistor, and the arduino mega will show the Temperature / humidity sensor
> Toolbox fix working reloading

- src/blocks/color/generators.ts
- src/blocks/rgbled/generators.ts
- src/core/blockly/generators/python.ts
- src/core/blockly/helpers/color.helper.ts
I have changed the main generator a bit so that we get syntactically correct code generation
> Completed RGB Block and improved code generation

- src/blocks/loops/generators.ts
- src/blocks/message/generators.ts
- src/microcontrollers/arduino_mega/profile.ts
- src/microcontrollers/arduino_uno/profile.ts
- Fixed the for loop
- Fixed the variables
> For Loop Variable Fixes
